name: Deploy to Minikube
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - uses: actions/checkout@v2
    
    - name: Start minikube
      uses: medyagh/setup-minikube@master
      
    - name: Build image inside Minikube environment
      run: |
        export SHELL=/bin/bash
        # This is the Magic Command:
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t devopshint/node-app:latest .
        
    - name: Deploy to Minikube
      run: kubectl apply -f k8s-node-app.yaml
      
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services
        # Wait a moment for pod to start
        sleep 15
        kubectl get pods
        minikube service nodejs-app --url
